// AUTO-GENERATED by scripts/generate-fp-exhaustive-table.mjs - do not edit by hand.
// Re-run: npm run build && node scripts/generate-fp-exhaustive-table.mjs
export type FixtureKind =
  | 'date'
  | 'dateArray'
  | 'interval'
  | 'duration'
  | 'isoDuration'
  | 'dateValues'
  | 'string'
  | 'timeZoneId'
  | 'number'
  | 'boolean'
  | 'options';

export interface FpExhaustiveCase {
  exportName: string;
  directExportName: string;
  onlyOptionsParam: boolean;
  args: { kind: FixtureKind; typeText: string }[];
}

export const fpExhaustiveTable: FpExhaustiveCase[] = [
  {
    exportName: 'add',
    directExportName: 'add',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'duration',
        typeText: 'Duration',
      },
    ],
  },
  {
    exportName: 'addBusinessDays',
    directExportName: 'addBusinessDays',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'addDays',
    directExportName: 'addDays',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'addHours',
    directExportName: 'addHours',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'addISOWeekYears',
    directExportName: 'addISOWeekYears',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'addMilliseconds',
    directExportName: 'addMilliseconds',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'addMinutes',
    directExportName: 'addMinutes',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'addMonths',
    directExportName: 'addMonths',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'addQuarters',
    directExportName: 'addQuarters',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'addSeconds',
    directExportName: 'addSeconds',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'addWeeks',
    directExportName: 'addWeeks',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'addYears',
    directExportName: 'addYears',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'areIntervalsOverlapping',
    directExportName: 'areIntervalsOverlapping',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
    ],
  },
  {
    exportName: 'areIntervalsOverlappingWithOptions',
    directExportName: 'areIntervalsOverlapping',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
      {
        kind: 'options',
        typeText: 'AreIntervalsOverlappingOptions | undefined',
      },
    ],
  },
  {
    exportName: 'clamp',
    directExportName: 'clamp',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
    ],
  },
  {
    exportName: 'closestIndexTo',
    directExportName: 'closestIndexTo',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'dateArray',
        typeText: 'readonly Date[]',
      },
    ],
  },
  {
    exportName: 'closestTo',
    directExportName: 'closestTo',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'dateArray',
        typeText: 'readonly Date[]',
      },
    ],
  },
  {
    exportName: 'compareAsc',
    directExportName: 'compareAsc',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'compareDesc',
    directExportName: 'compareDesc',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'constructNow',
    directExportName: 'constructNow',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'daysToWeeks',
    directExportName: 'daysToWeeks',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'differenceInBusinessDays',
    directExportName: 'differenceInBusinessDays',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'differenceInCalendarDays',
    directExportName: 'differenceInCalendarDays',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'differenceInCalendarISOWeekYears',
    directExportName: 'differenceInCalendarISOWeekYears',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'differenceInCalendarISOWeeks',
    directExportName: 'differenceInCalendarISOWeeks',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'differenceInCalendarMonths',
    directExportName: 'differenceInCalendarMonths',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'differenceInCalendarQuarters',
    directExportName: 'differenceInCalendarQuarters',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'differenceInCalendarWeeks',
    directExportName: 'differenceInCalendarWeeks',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'differenceInCalendarWeeksWithOptions',
    directExportName: 'differenceInCalendarWeeks',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'options',
        typeText: 'StartOfWeekOptions | undefined',
      },
    ],
  },
  {
    exportName: 'differenceInCalendarYears',
    directExportName: 'differenceInCalendarYears',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'differenceInDays',
    directExportName: 'differenceInDays',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'differenceInHours',
    directExportName: 'differenceInHours',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'differenceInISOWeekYears',
    directExportName: 'differenceInISOWeekYears',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'differenceInMilliseconds',
    directExportName: 'differenceInMilliseconds',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'differenceInMinutes',
    directExportName: 'differenceInMinutes',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'differenceInMonths',
    directExportName: 'differenceInMonths',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'differenceInQuarters',
    directExportName: 'differenceInQuarters',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'differenceInSeconds',
    directExportName: 'differenceInSeconds',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'differenceInWeeks',
    directExportName: 'differenceInWeeks',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'differenceInYears',
    directExportName: 'differenceInYears',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'eachDayOfInterval',
    directExportName: 'eachDayOfInterval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
    ],
  },
  {
    exportName: 'eachDayOfIntervalWithOptions',
    directExportName: 'eachDayOfInterval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
      {
        kind: 'options',
        typeText: 'EachOfIntervalOptions | undefined',
      },
    ],
  },
  {
    exportName: 'eachHourOfInterval',
    directExportName: 'eachHourOfInterval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
    ],
  },
  {
    exportName: 'eachHourOfIntervalWithOptions',
    directExportName: 'eachHourOfInterval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
      {
        kind: 'options',
        typeText: 'EachOfIntervalOptions | undefined',
      },
    ],
  },
  {
    exportName: 'eachMinuteOfInterval',
    directExportName: 'eachMinuteOfInterval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
    ],
  },
  {
    exportName: 'eachMinuteOfIntervalWithOptions',
    directExportName: 'eachMinuteOfInterval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
      {
        kind: 'options',
        typeText: 'EachOfIntervalOptions | undefined',
      },
    ],
  },
  {
    exportName: 'eachMonthOfInterval',
    directExportName: 'eachMonthOfInterval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
    ],
  },
  {
    exportName: 'eachMonthOfIntervalWithOptions',
    directExportName: 'eachMonthOfInterval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
      {
        kind: 'options',
        typeText: 'EachOfIntervalOptions | undefined',
      },
    ],
  },
  {
    exportName: 'eachQuarterOfInterval',
    directExportName: 'eachQuarterOfInterval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
    ],
  },
  {
    exportName: 'eachQuarterOfIntervalWithOptions',
    directExportName: 'eachQuarterOfInterval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
      {
        kind: 'options',
        typeText: 'EachOfIntervalOptions | undefined',
      },
    ],
  },
  {
    exportName: 'eachWeekOfInterval',
    directExportName: 'eachWeekOfInterval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
    ],
  },
  {
    exportName: 'eachWeekOfIntervalWithOptions',
    directExportName: 'eachWeekOfInterval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
      {
        kind: 'options',
        typeText: 'EachWeekOfIntervalOptions | undefined',
      },
    ],
  },
  {
    exportName: 'eachWeekendOfInterval',
    directExportName: 'eachWeekendOfInterval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
    ],
  },
  {
    exportName: 'eachWeekendOfMonth',
    directExportName: 'eachWeekendOfMonth',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'eachWeekendOfYear',
    directExportName: 'eachWeekendOfYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'eachYearOfInterval',
    directExportName: 'eachYearOfInterval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
    ],
  },
  {
    exportName: 'eachYearOfIntervalWithOptions',
    directExportName: 'eachYearOfInterval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
      {
        kind: 'options',
        typeText: 'EachOfIntervalOptions | undefined',
      },
    ],
  },
  {
    exportName: 'endOfDay',
    directExportName: 'endOfDay',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'endOfDecade',
    directExportName: 'endOfDecade',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'endOfHour',
    directExportName: 'endOfHour',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'endOfISOWeek',
    directExportName: 'endOfISOWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'endOfISOWeekYear',
    directExportName: 'endOfISOWeekYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'endOfMinute',
    directExportName: 'endOfMinute',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'endOfMonth',
    directExportName: 'endOfMonth',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'endOfQuarter',
    directExportName: 'endOfQuarter',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'endOfSecond',
    directExportName: 'endOfSecond',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'endOfTodayZonedDateTime',
    directExportName: 'endOfTodayZonedDateTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'timeZoneId',
        typeText: 'string | undefined',
      },
    ],
  },
  {
    exportName: 'endOfTomorrowZonedDateTime',
    directExportName: 'endOfTomorrowZonedDateTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'timeZoneId',
        typeText: 'string | undefined',
      },
    ],
  },
  {
    exportName: 'endOfWeek',
    directExportName: 'endOfWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'endOfWeekWithOptions',
    directExportName: 'endOfWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'options',
        typeText: 'StartOfWeekOptions | undefined',
      },
    ],
  },
  {
    exportName: 'endOfYear',
    directExportName: 'endOfYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'endOfYesterdayZonedDateTime',
    directExportName: 'endOfYesterdayZonedDateTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'timeZoneId',
        typeText: 'string | undefined',
      },
    ],
  },
  {
    exportName: 'format',
    directExportName: 'format',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
      {
        kind: 'string',
        typeText: 'string',
      },
    ],
  },
  {
    exportName: 'formatDistance',
    directExportName: 'formatDistance',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'formatDistanceStrict',
    directExportName: 'formatDistanceStrict',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'formatDistanceStrictWithOptions',
    directExportName: 'formatDistanceStrict',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'options',
        typeText: 'FormatDistanceStrictOptions | undefined',
      },
    ],
  },
  {
    exportName: 'formatDistanceToNow',
    directExportName: 'formatDistanceToNow',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
    ],
  },
  {
    exportName: 'formatDistanceToNowStrict',
    directExportName: 'formatDistanceToNowStrict',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
    ],
  },
  {
    exportName: 'formatDistanceToNowStrictWithOptions',
    directExportName: 'formatDistanceToNowStrict',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
      {
        kind: 'options',
        typeText: 'FormatDistanceStrictOptions | undefined',
      },
    ],
  },
  {
    exportName: 'formatDistanceToNowWithOptions',
    directExportName: 'formatDistanceToNow',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
      {
        kind: 'options',
        typeText: 'FormatDistanceOptions | undefined',
      },
    ],
  },
  {
    exportName: 'formatDistanceWithOptions',
    directExportName: 'formatDistance',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'options',
        typeText: 'FormatDistanceOptions | undefined',
      },
    ],
  },
  {
    exportName: 'formatDuration',
    directExportName: 'formatDuration',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'duration',
        typeText: 'Duration',
      },
    ],
  },
  {
    exportName: 'formatDurationWithOptions',
    directExportName: 'formatDuration',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'duration',
        typeText: 'Duration',
      },
      {
        kind: 'options',
        typeText: 'FormatDurationOptions | undefined',
      },
    ],
  },
  {
    exportName: 'formatISO',
    directExportName: 'formatISO',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
    ],
  },
  {
    exportName: 'formatISODuration',
    directExportName: 'formatISODuration',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'isoDuration',
        typeText: 'ISODuration',
      },
    ],
  },
  {
    exportName: 'formatISOWithOptions',
    directExportName: 'formatISO',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
      {
        kind: 'options',
        typeText: 'FormatISOOptions | undefined',
      },
    ],
  },
  {
    exportName: 'formatISO9075',
    directExportName: 'formatISO9075',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
    ],
  },
  {
    exportName: 'formatISO9075WithOptions',
    directExportName: 'formatISO9075',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
      {
        kind: 'options',
        typeText: 'FormatISO9075Options | undefined',
      },
    ],
  },
  {
    exportName: 'formatRelative',
    directExportName: 'formatRelative',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'formatRelativeWithOptions',
    directExportName: 'formatRelative',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'options',
        typeText: 'FormatRelativeOptions | undefined',
      },
    ],
  },
  {
    exportName: 'formatRFC3339',
    directExportName: 'formatRFC3339',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
    ],
  },
  {
    exportName: 'formatRFC3339WithOptions',
    directExportName: 'formatRFC3339',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
      {
        kind: 'options',
        typeText: 'FormatRFC3339Options | undefined',
      },
    ],
  },
  {
    exportName: 'formatRFC7231',
    directExportName: 'formatRFC7231',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'formatWithOptions',
    directExportName: 'format',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
      {
        kind: 'string',
        typeText: 'string',
      },
      {
        kind: 'options',
        typeText: 'FormatOptions | undefined',
      },
    ],
  },
  {
    exportName: 'fromUnixTime',
    directExportName: 'fromUnixTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'fromUnixTimePlainDateTime',
    directExportName: 'fromUnixTimePlainDateTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'fromUnixTimeZonedDateTime',
    directExportName: 'fromUnixTimeZonedDateTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
      {
        kind: 'timeZoneId',
        typeText: 'string | undefined',
      },
    ],
  },
  {
    exportName: 'getDate',
    directExportName: 'getDate',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getDay',
    directExportName: 'getDay',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getDayOfYear',
    directExportName: 'getDayOfYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getDaysInMonth',
    directExportName: 'getDaysInMonth',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getDaysInYear',
    directExportName: 'getDaysInYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getDecade',
    directExportName: 'getDecade',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getHours',
    directExportName: 'getHours',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getISODay',
    directExportName: 'getISODay',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getISOWeek',
    directExportName: 'getISOWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getISOWeekYear',
    directExportName: 'getISOWeekYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getISOWeeksInYear',
    directExportName: 'getISOWeeksInYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getMilliseconds',
    directExportName: 'getMilliseconds',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getMinutes',
    directExportName: 'getMinutes',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getMonth',
    directExportName: 'getMonth',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getOverlappingDaysInIntervals',
    directExportName: 'getOverlappingDaysInIntervals',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
    ],
  },
  {
    exportName: 'getQuarter',
    directExportName: 'getQuarter',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getSeconds',
    directExportName: 'getSeconds',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getTime',
    directExportName: 'getTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getUnixTime',
    directExportName: 'getUnixTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getWeek',
    directExportName: 'getWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getWeekOfMonth',
    directExportName: 'getWeekOfMonth',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getWeekOfMonthWithOptions',
    directExportName: 'getWeekOfMonth',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'options',
        typeText: 'LocalWeekOptions | undefined',
      },
    ],
  },
  {
    exportName: 'getWeekWithOptions',
    directExportName: 'getWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'options',
        typeText: 'LocalWeekOptions | undefined',
      },
    ],
  },
  {
    exportName: 'getWeekYear',
    directExportName: 'getWeekYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getWeekYearWithOptions',
    directExportName: 'getWeekYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'options',
        typeText: 'LocalWeekOptions | undefined',
      },
    ],
  },
  {
    exportName: 'getWeeksInMonth',
    directExportName: 'getWeeksInMonth',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'getWeeksInMonthWithOptions',
    directExportName: 'getWeeksInMonth',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'options',
        typeText: 'LocalWeekOptions | undefined',
      },
    ],
  },
  {
    exportName: 'getYear',
    directExportName: 'getYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'hoursToMilliseconds',
    directExportName: 'hoursToMilliseconds',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'hoursToMinutes',
    directExportName: 'hoursToMinutes',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'hoursToSeconds',
    directExportName: 'hoursToSeconds',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'interval',
    directExportName: 'interval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'intervalToDuration',
    directExportName: 'intervalToDuration',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
    ],
  },
  {
    exportName: 'intervalWithOptions',
    directExportName: 'interval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'options',
        typeText: 'IntervalOptions | undefined',
      },
    ],
  },
  {
    exportName: 'intlFormatDistance',
    directExportName: 'intlFormatDistance',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'intlFormatDistanceWithOptions',
    directExportName: 'intlFormatDistance',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'options',
        typeText: 'IntlFormatDistanceOptions | undefined',
      },
    ],
  },
  {
    exportName: 'isAfter',
    directExportName: 'isAfter',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isBefore',
    directExportName: 'isBefore',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isDate',
    directExportName: 'isDate',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'unknown',
      },
    ],
  },
  {
    exportName: 'isEqual',
    directExportName: 'isEqual',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isExists',
    directExportName: 'isExists',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'isFirstDayOfMonth',
    directExportName: 'isFirstDayOfMonth',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isFriday',
    directExportName: 'isFriday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isFuture',
    directExportName: 'isFuture',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
    ],
  },
  {
    exportName: 'isLastDayOfMonth',
    directExportName: 'isLastDayOfMonth',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isLeapYear',
    directExportName: 'isLeapYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isMatch',
    directExportName: 'isMatch',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'string',
        typeText: 'string',
      },
      {
        kind: 'string',
        typeText: 'string',
      },
    ],
  },
  {
    exportName: 'isMatchWithOptions',
    directExportName: 'isMatch',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'string',
        typeText: 'string',
      },
      {
        kind: 'string',
        typeText: 'string',
      },
      {
        kind: 'options',
        typeText: 'ParseOptions | undefined',
      },
    ],
  },
  {
    exportName: 'isMonday',
    directExportName: 'isMonday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isPast',
    directExportName: 'isPast',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
    ],
  },
  {
    exportName: 'isPlainDate',
    directExportName: 'isPlainDate',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'unknown',
      },
    ],
  },
  {
    exportName: 'isPlainDateTime',
    directExportName: 'isPlainDateTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'unknown',
      },
    ],
  },
  {
    exportName: 'isSameDay',
    directExportName: 'isSameDay',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isSameHour',
    directExportName: 'isSameHour',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isSameISOWeek',
    directExportName: 'isSameISOWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isSameISOWeekYear',
    directExportName: 'isSameISOWeekYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isSameMinute',
    directExportName: 'isSameMinute',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isSameMonth',
    directExportName: 'isSameMonth',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isSameQuarter',
    directExportName: 'isSameQuarter',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isSameSecond',
    directExportName: 'isSameSecond',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isSameWeek',
    directExportName: 'isSameWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isSameWeekWithOptions',
    directExportName: 'isSameWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'options',
        typeText: 'StartOfWeekOptions | undefined',
      },
    ],
  },
  {
    exportName: 'isSameYear',
    directExportName: 'isSameYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isSaturday',
    directExportName: 'isSaturday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isSunday',
    directExportName: 'isSunday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isTemporal',
    directExportName: 'isTemporal',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'unknown',
      },
    ],
  },
  {
    exportName: 'isThisHour',
    directExportName: 'isThisHour',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | TimeLike',
      },
    ],
  },
  {
    exportName: 'isThisISOWeek',
    directExportName: 'isThisISOWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
    ],
  },
  {
    exportName: 'isThisMinute',
    directExportName: 'isThisMinute',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | TimeLike',
      },
    ],
  },
  {
    exportName: 'isThisMonth',
    directExportName: 'isThisMonth',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
    ],
  },
  {
    exportName: 'isThisQuarter',
    directExportName: 'isThisQuarter',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
    ],
  },
  {
    exportName: 'isThisSecond',
    directExportName: 'isThisSecond',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | TimeLike',
      },
    ],
  },
  {
    exportName: 'isThisWeek',
    directExportName: 'isThisWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
    ],
  },
  {
    exportName: 'isThisWeekWithOptions',
    directExportName: 'isThisWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
      {
        kind: 'options',
        typeText: 'StartOfWeekOptions | undefined',
      },
    ],
  },
  {
    exportName: 'isThisYear',
    directExportName: 'isThisYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
    ],
  },
  {
    exportName: 'isThursday',
    directExportName: 'isThursday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isToday',
    directExportName: 'isToday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
    ],
  },
  {
    exportName: 'isTomorrow',
    directExportName: 'isTomorrow',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
    ],
  },
  {
    exportName: 'isTuesday',
    directExportName: 'isTuesday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isValid',
    directExportName: 'isValid',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'unknown',
      },
    ],
  },
  {
    exportName: 'isWednesday',
    directExportName: 'isWednesday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isWeekend',
    directExportName: 'isWeekend',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'isWithinInterval',
    directExportName: 'isWithinInterval',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'interval',
        typeText: 'Interval<Date>',
      },
    ],
  },
  {
    exportName: 'isYesterday',
    directExportName: 'isYesterday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
    ],
  },
  {
    exportName: 'isZonedDateTime',
    directExportName: 'isZonedDateTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'unknown',
      },
    ],
  },
  {
    exportName: 'lastDayOfDecade',
    directExportName: 'lastDayOfDecade',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'lastDayOfISOWeek',
    directExportName: 'lastDayOfISOWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'lastDayOfISOWeekYear',
    directExportName: 'lastDayOfISOWeekYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'lastDayOfMonth',
    directExportName: 'lastDayOfMonth',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'lastDayOfQuarter',
    directExportName: 'lastDayOfQuarter',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'lastDayOfWeek',
    directExportName: 'lastDayOfWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'lastDayOfWeekWithOptions',
    directExportName: 'lastDayOfWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'options',
        typeText: 'StartOfWeekOptions | undefined',
      },
    ],
  },
  {
    exportName: 'lastDayOfYear',
    directExportName: 'lastDayOfYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'lightFormat',
    directExportName: 'lightFormat',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
      {
        kind: 'string',
        typeText: 'string',
      },
    ],
  },
  {
    exportName: 'max',
    directExportName: 'max',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'dateArray',
        typeText: 'readonly Date[]',
      },
    ],
  },
  {
    exportName: 'milliseconds',
    directExportName: 'milliseconds',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'duration',
        typeText: 'Duration',
      },
    ],
  },
  {
    exportName: 'millisecondsToHours',
    directExportName: 'millisecondsToHours',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'millisecondsToMinutes',
    directExportName: 'millisecondsToMinutes',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'millisecondsToSeconds',
    directExportName: 'millisecondsToSeconds',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'min',
    directExportName: 'min',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'dateArray',
        typeText: 'readonly Date[]',
      },
    ],
  },
  {
    exportName: 'minutesToHours',
    directExportName: 'minutesToHours',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'minutesToMilliseconds',
    directExportName: 'minutesToMilliseconds',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'minutesToSeconds',
    directExportName: 'minutesToSeconds',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'monthsToQuarters',
    directExportName: 'monthsToQuarters',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'monthsToYears',
    directExportName: 'monthsToYears',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'nextDay',
    directExportName: 'nextDay',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'nextFriday',
    directExportName: 'nextFriday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'nextMonday',
    directExportName: 'nextMonday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'nextSaturday',
    directExportName: 'nextSaturday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'nextSunday',
    directExportName: 'nextSunday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'nextThursday',
    directExportName: 'nextThursday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'nextTuesday',
    directExportName: 'nextTuesday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'nextWednesday',
    directExportName: 'nextWednesday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'previousDay',
    directExportName: 'previousDay',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'previousFriday',
    directExportName: 'previousFriday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'previousMonday',
    directExportName: 'previousMonday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'previousSaturday',
    directExportName: 'previousSaturday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'previousSunday',
    directExportName: 'previousSunday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'previousThursday',
    directExportName: 'previousThursday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'previousTuesday',
    directExportName: 'previousTuesday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'previousWednesday',
    directExportName: 'previousWednesday',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'quartersToMonths',
    directExportName: 'quartersToMonths',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'quartersToYears',
    directExportName: 'quartersToYears',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'roundToNearestHours',
    directExportName: 'roundToNearestHours',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'roundToNearestHoursWithOptions',
    directExportName: 'roundToNearestHours',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'options',
        typeText: 'RoundToNearestHoursOptions | undefined',
      },
    ],
  },
  {
    exportName: 'roundToNearestMinutes',
    directExportName: 'roundToNearestMinutes',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'roundToNearestMinutesWithOptions',
    directExportName: 'roundToNearestMinutes',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'options',
        typeText: 'RoundToNearestMinutesOptions | undefined',
      },
    ],
  },
  {
    exportName: 'secondsToHours',
    directExportName: 'secondsToHours',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'secondsToMilliseconds',
    directExportName: 'secondsToMilliseconds',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'secondsToMinutes',
    directExportName: 'secondsToMinutes',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'set',
    directExportName: 'set',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'dateValues',
        typeText: 'DateValues',
      },
    ],
  },
  {
    exportName: 'setDate',
    directExportName: 'setDate',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'setDay',
    directExportName: 'setDay',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'setDayOfYear',
    directExportName: 'setDayOfYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'setDayWithOptions',
    directExportName: 'setDay',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
      {
        kind: 'options',
        typeText: 'StartOfWeekOptions | undefined',
      },
    ],
  },
  {
    exportName: 'setDefaultOptions',
    directExportName: 'setDefaultOptions',
    onlyOptionsParam: true,
    args: [
      {
        kind: 'options',
        typeText: 'SetDefaultOptions',
      },
    ],
  },
  {
    exportName: 'setHours',
    directExportName: 'setHours',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'setISODay',
    directExportName: 'setISODay',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'setISOWeek',
    directExportName: 'setISOWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'setISOWeekYear',
    directExportName: 'setISOWeekYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'setMilliseconds',
    directExportName: 'setMilliseconds',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'setMinutes',
    directExportName: 'setMinutes',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'setMonth',
    directExportName: 'setMonth',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'setQuarter',
    directExportName: 'setQuarter',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'setSeconds',
    directExportName: 'setSeconds',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'setWeek',
    directExportName: 'setWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'setWeekWithOptions',
    directExportName: 'setWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
      {
        kind: 'options',
        typeText: 'LocalWeekOptions | undefined',
      },
    ],
  },
  {
    exportName: 'setWeekYear',
    directExportName: 'setWeekYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'setWeekYearWithOptions',
    directExportName: 'setWeekYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
      {
        kind: 'options',
        typeText: 'LocalWeekOptions | undefined',
      },
    ],
  },
  {
    exportName: 'setYear',
    directExportName: 'setYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'startOfDay',
    directExportName: 'startOfDay',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'startOfDecade',
    directExportName: 'startOfDecade',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'startOfHour',
    directExportName: 'startOfHour',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'startOfISOWeek',
    directExportName: 'startOfISOWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'startOfISOWeekYear',
    directExportName: 'startOfISOWeekYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'startOfMinute',
    directExportName: 'startOfMinute',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'startOfMonth',
    directExportName: 'startOfMonth',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'startOfQuarter',
    directExportName: 'startOfQuarter',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'startOfSecond',
    directExportName: 'startOfSecond',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'startOfTodayZonedDateTime',
    directExportName: 'startOfTodayZonedDateTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'timeZoneId',
        typeText: 'string | undefined',
      },
    ],
  },
  {
    exportName: 'startOfTomorrowZonedDateTime',
    directExportName: 'startOfTomorrowZonedDateTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'timeZoneId',
        typeText: 'string | undefined',
      },
    ],
  },
  {
    exportName: 'startOfWeek',
    directExportName: 'startOfWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'startOfWeekWithOptions',
    directExportName: 'startOfWeek',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'options',
        typeText: 'StartOfWeekOptions | undefined',
      },
    ],
  },
  {
    exportName: 'startOfWeekYear',
    directExportName: 'startOfWeekYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'startOfWeekYearWithOptions',
    directExportName: 'startOfWeekYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'options',
        typeText: 'LocalWeekOptions | undefined',
      },
    ],
  },
  {
    exportName: 'startOfYear',
    directExportName: 'startOfYear',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
    ],
  },
  {
    exportName: 'startOfYesterdayZonedDateTime',
    directExportName: 'startOfYesterdayZonedDateTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'timeZoneId',
        typeText: 'string | undefined',
      },
    ],
  },
  {
    exportName: 'sub',
    directExportName: 'sub',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'duration',
        typeText: 'Duration',
      },
    ],
  },
  {
    exportName: 'subBusinessDays',
    directExportName: 'subBusinessDays',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'subDays',
    directExportName: 'subDays',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'subHours',
    directExportName: 'subHours',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'subISOWeekYears',
    directExportName: 'subISOWeekYears',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'subMilliseconds',
    directExportName: 'subMilliseconds',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'subMinutes',
    directExportName: 'subMinutes',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'subMonths',
    directExportName: 'subMonths',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'subQuarters',
    directExportName: 'subQuarters',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'subSeconds',
    directExportName: 'subSeconds',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'subWeeks',
    directExportName: 'subWeeks',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'subYears',
    directExportName: 'subYears',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date',
      },
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'toDate',
    directExportName: 'toDate',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'unknown',
      },
    ],
  },
  {
    exportName: 'toPlainDate',
    directExportName: 'toPlainDate',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
    ],
  },
  {
    exportName: 'toPlainDateTime',
    directExportName: 'toPlainDateTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
    ],
  },
  {
    exportName: 'toZonedDateTime',
    directExportName: 'toZonedDateTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'date',
        typeText: 'Date | DateLike',
      },
      {
        kind: 'timeZoneId',
        typeText: 'string',
      },
    ],
  },
  {
    exportName: 'todayZonedDateTime',
    directExportName: 'todayZonedDateTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'timeZoneId',
        typeText: 'string | undefined',
      },
    ],
  },
  {
    exportName: 'tomorrowZonedDateTime',
    directExportName: 'tomorrowZonedDateTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'timeZoneId',
        typeText: 'string | undefined',
      },
    ],
  },
  {
    exportName: 'weeksToDays',
    directExportName: 'weeksToDays',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'yearsToDays',
    directExportName: 'yearsToDays',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'yearsToMonths',
    directExportName: 'yearsToMonths',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'yearsToQuarters',
    directExportName: 'yearsToQuarters',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'number',
        typeText: 'number',
      },
    ],
  },
  {
    exportName: 'yesterdayZonedDateTime',
    directExportName: 'yesterdayZonedDateTime',
    onlyOptionsParam: false,
    args: [
      {
        kind: 'timeZoneId',
        typeText: 'string | undefined',
      },
    ],
  },
];
